# Generated by Django 2.0.7 on 2018-07-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180707_1340'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(default='X', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DepartmentBranches'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Departments'),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment_no',
            field=models.CharField(default='A2305216324', max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='registration_year',
            field=models.CharField(default=2016, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(default='5', max_length=2),
            preserve_default=False,
        ),
    ]
