# Generated by Django 2.0.7 on 2018-07-07 14:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180707_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 7, 7, 14, 6, 16, 441725, tzinfo=utc), help_text='Your Date of Birth', verbose_name='date of birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(help_text='Class Batch e.g. X or Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(help_text='Select your Branch e.g. ASET - CSE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DepartmentBranches'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(help_text='Select your department e.g. ASET', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Departments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Your Primary Email Address', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrollment_no',
            field=models.CharField(help_text='Your Amity Enrollment Number', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Select your gender, wisely.', max_length=6, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, help_text='Enter your mobile number, WhatsApp Preferred.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_year',
            field=models.CharField(help_text='Year of Joining Amity', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(help_text='Section Number e.g. 5', max_length=2),
        ),
    ]
