# Generated by Django 2.0.7 on 2018-07-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180707_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentbranches',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
