# Generated by Django 2.0.7 on 2018-07-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20180720_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubroles',
            name='label',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubroles',
            name='mutable',
            field=models.BooleanField(default=True),
        ),
    ]
