# Generated by Django 2.0.7 on 2018-07-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20180720_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmemberroles',
            name='club',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='club.Club'),
            preserve_default=False,
        ),
    ]
