# Generated by Django 2.0.7 on 2018-07-23 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0008_auto_20180723_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmemberroles',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmemberroles',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
