# Generated by Django 2.0.7 on 2018-07-25 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0009_auto_20180723_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='OD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='participant', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_event', to='club.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ODSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ODSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('timeSlotStart', models.DateTimeField()),
                ('timeSlotEnd', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user', to=settings.AUTH_USER_MODEL)),
                ('od', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.OD')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='odsubjects',
            unique_together={('od', 'subject', 'timeSlotStart')},
        ),
        migrations.AlterUniqueTogether(
            name='od',
            unique_together={('user', 'event')},
        ),
    ]
